### ISSUE TITLE
Use latest AMIs

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs-buildbot#1]
One of the limitations of the buildbot infrastructure is that to keep current the `master.cfg` must be updated manually as new AMIs are published.  The buildbot documentation described ami filters as the solution to this issue.  We should investigating using them in our `master.cfg`, see:

http://docs.buildbot.net/latest/manual/cfg-buildslaves-ec2.html

**Comment by Conan-Kudo** [comment]
This is something I'm definitely interested in working on, because it's a royal pain to keep things up to date without an interruption of service which causes all kinds of problems.

**Comment by behlendorf** [comment]
A version of this functionality has been added for the FreeBSD AMIs and we should consider extending it for Linux.  See commit 2263ee93dfd670f06e416430cdb6dbfe498d3e97 for details.

**Comment by Conan-Kudo** [comment]
@behlendorf I've been working off and on in wiring up buildbot to receive the latest AMI ID from Fedora infrastructure for Fedora images. I'm also trying to figure out a way to get that info for CentOS too.
