### ISSUE TITLE
Is there a known-issues.html with PRs?

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs-buildbot#239]
I see that known-issues.sh knows how to generate the page with PR failures included, but that that option presumably isn't being used [here](http://build.zfsonlinux.org/known-issues.html).

Is there/could there be a version of that page added to whatever cron generates it that includes PRs, perhaps with a shorter timescale (e.g. 7/14 days)? I suspect it would make things like the issues behind openzfs/zfs#12663 or #238 flamingly obvious...

**Comment by rincebrain** [comment]
Neat, thanks for humoring my suggestion.

It seems to be doing something strange, though - e.g. [here](http://build.zfsonlinux.org/known-issues-with-pr-7.html) it's seeing failures from 'tests/funct,79:0ional/cli_root/zpool_expand/zpool_expand_001_pos'. I don't immediately see anywhere in the logfiles that's coming from - my guess would be if it were doing grep --color implicitly somewhere, though 79 doesn't ring any bells for any sequence I recognize...

It's also only for zpool_expand tests, and I don't obviously see something in the logs causing that...,hm.

**Comment by behlendorf** [comment]
Yes, I've noticed that in the past as well.  It's not always limited to the expand tests, I seen it elsewhere.  Though I never did determine where it's coming from.
