### ISSUE TITLE
Add builders for 13-RELEASE and without --enable-debug per platform?

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs-buildbot#248]
Differences between FBSD 13-RELEASE and 13-STABLE and --enable-debug versus not resulted in openzfs/zfs#13145, where building on 13-RELEASE was broken in two places and the CI hadn't noticed.

It'd be nice if non-debug builds didn't break without the CI noticing.

(While I'm asking for ponies, maybe a Debian 11 or sid builder so things like #13083 and #13103 are found sooner?)

**Comment by behlendorf** [comment]
There are definitely a lot of build combinations and it would be nice to verify them with the CI.  If we limited this to just compilation testing, we could probably use GitHub Actions and containers to at least do more Linux distribution testing.  It should also be easier for us to maintain and extend.  Though last I checked we'd still need to use the buildbot for FreeBSD.
