### ISSUE TITLE
Add install-fedora-on-zfs

### ISSUE THREAD

**Issue by Rudd-O** [openzfs/zfs-buildbot#33]
The project https://github.com/Rudd-O/install-fedora-on-zfs has the ability to build a bootable disk image that boots from ZFS (and LUKS beneath it, if so desired).  I do not know how buildbot works so I can't at this time produce a pull request to do it, but here's the details:
- script source: master branch from the above URL
- script inputs: --with-prebuilt-rpms=path/to/splandzfs/rpms/ --releasever=fedora-releasever
- script output: root.img (positional parameter)

The script will boot-cycle the root.img two times — one to test that the no-hostonly initrd works fine, and another to test that the hostonly initrd works fine.  This happens automatically within QEMU and requires no intervention (but, in the event that the boot process fails, QEMU will be killed after 12 minutes by the script).

Everything the script does is logged in detail, so diagnosing and reproducing any issue is trivial after that.

**Comment by dinatale2** [comment]
I cannot browse to your project. Is it a private repository? I can try and take a look at this sometime this week.

**Comment by Rudd-O** [comment]
I'm an idiot and wrote the wrong URL:

https://github.com/Rudd-O/zfs-fedora-installer

Corrected.

**Comment by Rudd-O** [comment]
Here a sample the command line that I use for my own testing:

```
sudo ./install-fedora-on-zfs --use-prebuilt-rpms=rpms/ --releasever=24 --yum-cachedir=/var/cache/privyumcache --host-name=localhost.localdomain --pool-name=test_24_RPMs --vol-size=6144 --swap-size=256 --root-password=password --luks-password=password --chown=rudd-o --chgrp=rudd-o root.img
```

**Comment by Rudd-O** [comment]
Take a look at this?

https://github.com/Rudd-O/zfs-buildbot/commits/master

**Comment by dinatale2** [comment]
Awesome! I glanced at it and I see what you're going for. I will look into trying to get this working in a test environment soon. I'll post back with questions.
